stages:
  - tests
  - deploy

.template: &defaults_gnu
  tags:
    - flexitag
  artifacts:
    name: "${CI_PIPELINE_ID}-${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}"
    expire_in: 1 day
    when: on_failure
    paths:
      - build_gnu
  cache:
    key: "${CI_COMMIT_REF_SLUG}-GNU"
    paths:
      - build_gnu
    policy: pull
  allow_failure: false

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "tests": Runs unit tests
# ----------------------------------------------------------------------------------------------------------------------------------------------------
tests:
  stage: tests
  tags:
    - flexitag
  before_script:
    - python3 -m pip install virtualenv
    - python3 -m virtualenv venv
    - . venv/bin/activate
    - python -m pip install pdoc tensorflow tf-agents numpy pyyaml matplotlib pytest pytest-cov
  script:
    - pytest -v --cov=src/relexi/
    - coverage xml -o reports/coverage.xml
  artifacts:
    paths:
      - reports/coverage.xml
    reports:
      cobertura:
        - reports/coverage.xml

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "deploy": Copies the repository to github
# ----------------------------------------------------------------------------------------------------------------------------------------------------
github:
  stage: deploy
  tags:
    - flexitag
  rules:
    - if: '$DO_DEPLOY && $CI_SERVER_URL =~ /.*\.iag\.uni-stuttgart\.de$/'
  script:
    - git clone --single-branch git@gitlab.iag.uni-stuttgart.de:flexi/codes/relexi.git relexi_github ; cd relexi_github ; git push --mirror git@github.com:flexi-framework/relexi.git ; cd ../
